In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_boston

In [2]:
# This problem has the following features: 
# 1. Frequency, in Hertzs. 
# 2. Angle of attack, in degrees. 
# 3. Chord length, in meters. 
# 4. Free-stream velocity, in meters per second. 
# 5. Suction side displacement thickness, in meters. 

# The only output is: 
# 6. Scaled sound pressure level, in decibels. 

In [3]:
feature_names = ['Frequency','Angle','Chord Length','velocity','displacement thickness','sound pressure']
airfoil = pd.read_csv("./airfoil_self_noise.csv",header=None,sep='\t',names=feature_names)

In [4]:
airfoil.head()

Frequency  Angle  Chord Length  velocity  displacement thickness  \
0        800    0.0        0.3048      71.3                0.002663   
1       1000    0.0        0.3048      71.3                0.002663   
2       1250    0.0        0.3048      71.3                0.002663   
3       1600    0.0        0.3048      71.3                0.002663   
4       2000    0.0        0.3048      71.3                0.002663   

   sound pressure  
0         126.201  
1         125.201  
2         125.951  
3         127.591  
4         127.461

In [5]:
airfoil = pd.DataFrame(airfoil)
airfoil.head()

Frequency  Angle  Chord Length  velocity  displacement thickness  \
0        800    0.0        0.3048      71.3                0.002663   
1       1000    0.0        0.3048      71.3                0.002663   
2       1250    0.0        0.3048      71.3                0.002663   
3       1600    0.0        0.3048      71.3                0.002663   
4       2000    0.0        0.3048      71.3                0.002663   

   sound pressure  
0         126.201  
1         125.201  
2         125.951  
3         127.591  
4         127.461

In [6]:
features = airfoil.loc[:,:'displacement thickness']
features.head()

Frequency  Angle  Chord Length  velocity  displacement thickness
0        800    0.0        0.3048      71.3                0.002663
1       1000    0.0        0.3048      71.3                0.002663
2       1250    0.0        0.3048      71.3                0.002663
3       1600    0.0        0.3048      71.3                0.002663
4       2000    0.0        0.3048      71.3                0.002663

In [7]:
frequency = pd.Series(airfoil['Frequency'])
frequency.value_counts().sort_values()

20000      6
16000     13
12500     25
200       35
250       42
10000     42
8000      52
315       56
400       69
500       78
630       88
6300      89
5000      95
800       97
1000      99
1250     100
4000     102
1600     103
3150     103
2500     104
2000     105
Name: Frequency, dtype: int64

In [8]:
data = pd.DataFrame(airfoil)
data.nunique()  # no. of unique values of each feature

Frequency                   21
Angle                       27
Chord Length                 6
velocity                     4
displacement thickness     105
sound pressure            1456
dtype: int64

In [9]:
corelation = airfoil.corr('pearson') 

In [10]:
corelation['sound pressure'].sort_values()

Frequency                -0.390711
displacement thickness   -0.312670
Chord Length             -0.236162
Angle                    -0.156108
velocity                  0.125103
sound pressure            1.000000
Name: sound pressure, dtype: float64

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler = MinMaxScaler()

In [13]:
y = airfoil['sound pressure']
y = y.reshape(-1,1)

C:\Users\Shilpa\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  


In [14]:
y = scaler.fit_transform(y)

In [15]:
from sklearn.model_selection import train_test_split 

In [16]:
x_train,x_test,y_train,y_test = train_test_split(features,y,test_size=0.2)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
regressor = LinearRegression() 

In [19]:
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
y_pred = regressor.predict(x_test)

In [21]:
for i in zip(y_pred,y_test):
    print(i)

(array([0.58482202]), array([0.85058633]))
(array([0.65195784]), array([0.75589651]))
(array([0.46604746]), array([0.410748]))
(array([0.47736286]), array([0.54609514]))
(array([0.78540538]), array([0.73199138]))
(array([0.78956688]), array([0.77685005]))
(array([0.65569139]), array([0.58411998]))
(array([0.70968333]), array([0.67362459]))
(array([0.42758262]), array([0.25872843]))
(array([0.44414157]), array([0.35841732]))
(array([0.56846611]), array([0.73268275]))
(array([0.35192827]), array([0.4104555]))
(array([0.44485719]), array([0.42531975]))
(array([0.61239076]), array([0.55728987]))
(array([0.6398071]), array([0.47241205]))
(array([0.76347208]), array([0.58691201]))
(array([0.61418137]), array([0.75743877]))
(array([0.57464906]), array([0.54402106]))
(array([0.80026347]), array([0.72122211]))
(array([0.64261226]), array([0.58023772]))
(array([0.70737401]), array([0.7177919]))
(array([0.77993535]), array([0.75666764]))
(array([0.72375528]), array([0.8038663]))
(array([0.6578051

In [22]:
from sklearn.metrics import mean_squared_error, r2_score

In [23]:
mean_squared_error(y_test,y_pred)

0.015195555745223145

In [24]:
r2_score(y_test,y_pred)   # it tells that if there are 100 pts then 56 pts are fit correctly

0.4796085537360655

In [25]:
y_pred.shape

(301, 1)

In [26]:
y_test.shape

(301, 1)