In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
gp = pd.read_csv("./googleplaystore.csv")

In [3]:
# dropping columns
gp = gp.drop(['Category','Last Updated','Current Ver'],axis=1)

In [4]:
gp.head()

App  Rating Reviews  Size  \
0     Photo Editor & Candy Camera & Grid & ScrapBook     4.1     159   19M   
1                                Coloring book moana     3.9     967   14M   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...     4.7   87510  8.7M   
3                              Sketch - Draw & Paint     4.5  215644   25M   
4              Pixel Draw - Number Art Coloring Book     4.3     967  2.8M   

      Installs  Type Price Content Rating                     Genres  \
0      10,000+  Free     0       Everyone               Art & Design   
1     500,000+  Free     0       Everyone  Art & Design;Pretend Play   
2   5,000,000+  Free     0       Everyone               Art & Design   
3  50,000,000+  Free     0           Teen               Art & Design   
4     100,000+  Free     0       Everyone    Art & Design;Creativity   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [5]:
# filling all the Nan values with the mean of that column values
gp = gp.fillna(gp.mean())

In [6]:
gp.isna().sum()

App               0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
Android Ver       3
dtype: int64

In [7]:
# these rows with null values still exist since mean of their column cannot be applied to the text data.

gp1 = gp[gp.isnull().any(axis=1)]
gp1

App     Rating Reviews  \
4453                    [substratum] Vacuum: P   4.400000     230   
4490                      Pi Dark [substratum]   4.500000     189   
9148                 Command & Conquer: Rivals   4.193338       0   
10472  Life Made WI-Fi Touchscreen Photo Frame  19.000000    3.0M   

                     Size Installs  Type     Price Content Rating  \
4453                  11M   1,000+  Paid     $1.49       Everyone   
4490                 2.1M  10,000+  Free         0       Everyone   
9148   Varies with device        0   NaN         0   Everyone 10+   
10472              1,000+     Free     0  Everyone            NaN   

                  Genres         Android Ver  
4453     Personalization                 NaN  
4490     Personalization                 NaN  
9148            Strategy  Varies with device  
10472  February 11, 2018                 NaN

In [8]:
gp.loc[gp['Installs']=='Free']

App  Rating Reviews    Size  \
10472  Life Made WI-Fi Touchscreen Photo Frame    19.0    3.0M  1,000+   

      Installs Type     Price Content Rating             Genres Android Ver  
10472     Free    0  Everyone            NaN  February 11, 2018         NaN

In [9]:
# the above row is deleted since installs has a value free which is insensible

#gp = gp.drop([10472],axis=0)

In [10]:
# removing , and + from Installs column
install =[]
for i in gp['Installs']:
    j = i.replace("+","")
    h = j.replace(",","")
    install.append(h)
install = pd.DataFrame(install,columns=['install'])

In [11]:
# from sklearn.preprocessing import MultiLabelBinarizer
# mlb = MultiLabelBinarizer()

In [12]:
# install1 = np.array(install)
# install2 = mlb.fit_transform(install1)

In [13]:
# mlb.classes_

In [14]:
# len(mlb.classes_)

In [15]:
# install2 = pd.DataFrame(install2)

In [16]:
# from sklearn.decomposition import PCA

In [17]:
# pca = PCA(n_components =1)
# install2 = pca.fit_transform(install2)

In [18]:
# install2 = pd.DataFrame(install2,columns=['install'])

In [19]:
install.head()

install
0     10000
1    500000
2   5000000
3  50000000
4    100000

In [20]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [21]:
# since there was a warning i used ravel
install = np.ravel(install)
install1 = le.fit_transform(install)

In [22]:
np.unique(install1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20], dtype=int64)

In [23]:
install1 = pd.DataFrame(install1,columns=['install'])
install1.head()

install
0        5
1       16
2       17
3       18
4        6

In [24]:
app = gp['App']
app = le.fit_transform(app)
app

array([6963, 2632, 8657, ..., 6892, 8395, 9487], dtype=int64)

In [25]:
np.unique(app)

array([   0,    1,    2, ..., 9657, 9658, 9659], dtype=int64)

In [26]:
app = pd.DataFrame(app)
app.head()

0
0  6963
1  2632
2  8657
3  7828
4  7023

In [27]:
gp_app=gp['App'].shape